apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang-microservice
  template:
    metadata:
      labels:
        app: golang-microservice
    spec:
      
      containers:
      - name: golang-microservice
        image: gcr.io/ci-cah/golang-microservice:latest 
        ports:
          - containerPort: 8080
        
        # 'env' is a property of the container, so it must be indented here
        env:
          - name: PORT
            value: "8080"

        # Liveness probe is a property of the container, indented here
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 15
          failureThreshold: 3

        # Readiness probe is a property of the container, indented here
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 2

        # Resources are properties of the container, indented here
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"