apiVersion: v1
kind: Service
metadata:
  name: golang-microservice
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '8080'
    
spec:
  selector:
    app: golang-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer