apiVersion: v1
kind: Service
metadata:
  name: golang-microservice-service
spec:
  selector:
    app: golang-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
