name: CI/CD to GKE

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Run Go tests
      run: go test ./...

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Verify gcloud authentication
      run: |
        gcloud auth list
        gcloud config list project

    - name: Configure Docker to use Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Build Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/golang-microservice/golang-microservice:${{ github.sha }} .

    - name: Push Docker image to GCR
      run: |
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/golang-microservice/golang-microservice:${{ github.sha }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Check runner architecture
      run: uname -m
    
    - name: Install gke-gcloud-auth-plugin
      run: |
        curl -Lo gke-gcloud-auth-plugin https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/gke-gcloud-auth-plugin
        chmod +x gke-gcloud-auth-plugin
        sudo mv gke-gcloud-auth-plugin /usr/local/bin/

    - name: Configure gcloud to use gke-gcloud-auth-plugin
      run: |
        gcloud config set container/use_client_certificate False
    
    - name: Install Google Cloud SDK with gke-gcloud-auth-plugin
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        export_default_credentials: true

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
          --zone ${{ secrets.GKE_ZONE }} \
          --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/golang-microservice \
          golang-microservice=gcr.io/${{ secrets.GCP_PROJECT_ID }}/golang-microservice:${{ github.sha }} \
          --record

        kubectl rollout status deployment/golang-microservice