name: CI/CD to GKE

on:
  push:
    branches:
      - main

# Define environment variables for the whole job
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  ARTIFACT_REGISTRY_REPO: golang-microservice # The name of your Artifact Registry repo
  DOCKER_IMAGE_NAME: golang-microservice   # The name of your image

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    # Add permissions for the GHA token to authenticate to GCP
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # ------------------- GO BUILD & TEST -------------------
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Run Go tests
      run: go test ./...

    # ------------------- GCP AUTH & SETUP -------------------
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        # If using Workload Identity Federation (recommended)
        workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_WIF_POOL_ID }}/providers/${{ secrets.GCP_WIF_PROVIDER_ID }}'
        service_account: '${{ secrets.GCP_SA_EMAIL }}'
        # If you must use a service account key (less secure)
        # credentials_json: '${{ secrets.GCP_SA_KEY }}'

    # This single step installs gcloud, kubectl, and the gke-gcloud-auth-plugin correctly for the runner's architecture.
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    # ------------------- DOCKER BUILD & PUSH -------------------
    - name: Configure Docker to use Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Build Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push us-central1-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}

    # ------------------- GKE DEPLOYMENT -------------------
    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER_NAME }} \
          --zone ${{ env.GKE_ZONE }}

    - name: Deploy to GKE
      run: |
        # Note: The image path should match exactly what you pushed to Artifact Registry
        kubectl set image deployment/golang-microservice \
          golang-microservice=us-central1-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}

    - name: Verify deployment rollout
      run: kubectl rollout status deployment/golang-microservice