name: CI/CD to GKE

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Run Go tests
      run: go test ./...

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Verify gcloud authentication
      run: |
        gcloud auth list
        gcloud config list project

    - name: Configure Docker to use Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Build Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/golang-microservice/golang-microservice:${{ github.sha }} .

    - name: Push Docker image to Artifact Registry
      run: |
         docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/golang-microservice/golang-microservice:${{ github.sha }}

    # STEP 1: Install the gcloud CLI first. This also installs kubectl.
    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        export_default_credentials: true
    
    - name: Install gke-gcloud-auth-plugin (architecture-aware)
      run: |
        ARCH=$(uname -m)
        if [ "$ARCH" = "x86_64" ]; then
          ARCH_ALIAS="amd64"
        elif [ "$ARCH" = "aarch64" ]; then
          ARCH_ALIAS="arm64"
        else
          echo "Unsupported architecture: $ARCH"
          exit 1
        fi

        # Download and install the correct binary, overwriting the one from setup-gcloud
        gcloud components install gke-gcloud-auth-plugin --quiet

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
          --zone ${{ secrets.GKE_ZONE }} \
          --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/golang-microservice \
          golang-microservice=gcr.io/${{ secrets.GCP_PROJECT_ID }}/golang-microservice:${{ github.sha }} 

        kubectl rollout status deployment/golang-microservice